# Generated by Django 5.1.1 on 2024-11-18 05:57

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default.svg', max_length=255, null=True, storage=storages.backends.s3.S3Storage, upload_to='avatar/'),
        ),
    ]
