# Generated by Django 5.1.1 on 2024-11-18 05:58

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='https://vuedjangochats3.s3.ap-northeast-1.amazonaws.com/avatar/default.svg', max_length=255, null=True, storage=storages.backends.s3.S3Storage, upload_to='avatar/'),
        ),
    ]
