# Generated by Django 5.1.1 on 2024-11-14 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_is_system_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominvite',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.room'),
        ),
    ]
