# Generated by Django 5.1.1 on 2024-11-18 05:57

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_roominvite_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='img',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage, upload_to='message/'),
        ),
    ]
